use anyhow::Result;
use std::path::PathBuf;
use serde::Deserialize;
use std::fs;

#[derive(Debug, Default, Deserialize)]
#[serde(default)]
pub struct ConfigFile {
    pub db_path: Option<String>,
    pub max_file_size: Option<u64>,
    pub model_id: Option<String>,
    pub model_cache_dir: Option<String>,
    pub embedding_batch_size: Option<usize>,
    pub default_search_limit: Option<usize>,
    pub watcher_debounce_ms: Option<u64>,
}

#[derive(Debug, Clone)]
pub struct Config {
    pub project_root: PathBuf,
    pub db_path: PathBuf,
    pub model_cache_dir: PathBuf,
    pub max_file_size: u64,
    pub model_id: String,
    pub embedding_batch_size: usize,
    pub default_search_limit: usize,
    pub watcher_debounce_ms: u64,
}

impl Config {
    /// Detect project root using (in order):
    ///   1. CLAUDE_PROJECT_DIR env var (set by Claude Code)
    ///   2. Walk up from CWD looking for project markers (.git, package.json, etc.)
    ///   3. Fall back to CWD
    pub fn detect_project_root() -> PathBuf {
        if let Ok(dir) = std::env::var("CLAUDE_PROJECT_DIR") {
            let p = PathBuf::from(dir);
            if p.is_dir() {
                return p;
            }
        }

        let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
        let mut current: &std::path::Path = cwd.as_ref();

        for _ in 0..8 {
            let markers = [".git", "package.json", "pyproject.toml", "Cargo.toml", "go.mod", "pom.xml"];
            if markers.iter().any(|m| current.join(m).exists()) {
                return current.to_path_buf();
            }
            current = match current.parent() {
                Some(p) => p,
                None => break,
            };
        }

        cwd
    }

    /// Load config from rindex.toml + env vars + defaults.
    pub fn load() -> Result<Self> {
        let project_root = Self::detect_project_root();

        // Load config file from project root, then ~/.config/rindex/config.toml
        let config_file: ConfigFile = {
            let candidates = [
                Some(project_root.join("rindex.toml")),
                dirs::config_dir().map(|d| d.join("rindex/config.toml")),
            ];
            candidates.iter().flatten().find_map(|p| fs::read_to_string(p).ok())
                .and_then(|content| toml::from_str(&content).ok())
                .unwrap_or_default()
        };

        let cache_dir = dirs::data_dir()
            .unwrap_or_else(|| PathBuf::from("."))
            .join("rindex");

        Ok(Self {
            project_root,
            db_path: config_file.db_path.map(PathBuf::from)
                .unwrap_or_else(|| cache_dir.join("rindex.db")),
            model_cache_dir: config_file.model_cache_dir
                .map(PathBuf::from)
                .unwrap_or_else(|| cache_dir.join("models")),
            max_file_size: config_file.max_file_size.unwrap_or(1_048_576),
            model_id: config_file.model_id
                .unwrap_or_else(|| "c2llm-static-256".to_string()),
            // Model is a local directory under model_cache_dir containing:
            //   token_embeddings.safetensors, tokenizer.json, config.json
            // Generated by: python scripts/distill.py --output <model_cache_dir>/c2llm-static-256/
            embedding_batch_size: config_file.embedding_batch_size.unwrap_or(32),
            default_search_limit: config_file.default_search_limit.unwrap_or(10),
            watcher_debounce_ms: config_file.watcher_debounce_ms.unwrap_or(500),
        })
    }
}
